CINDER_PATH = '../cinder/'

env = Environment()

env['APP_TARGET'] = 'MetronomeApp'
env['APP_SOURCES'] = ['MetronomeApp.cpp', 'ChannelView.cpp',
		'Config.cpp', 'OniCameraManager.cpp', 'ParamsUtils.cpp']
env['RESOURCES'] = ['squares.png']
env['DEBUG'] = 0

env = SConscript('../blocks/Cinder-NI/scons/SConscript', exports = 'env')

SConscript(CINDER_PATH + '/scons/SConscript', exports = 'env')
