CINDER_PATH = '../cinder/'

env = Environment()

env['APP_TARGET'] = 'MetronomeApp'
env['APP_SOURCES'] = ['MetronomeApp.cpp', 'CellDetector.cpp', 'ChannelView.cpp',
		'Config.cpp', 'OniCameraManager.cpp', 'ParamsUtils.cpp', 'Sound.cpp']
env['RESOURCES'] = ['baseImage10x10.png', 'customImage.png', 'customImageAlpha.png',
		'patternImage.png', 'patternImageAlpha.png']
env['DEBUG'] = 0

env = SConscript('../blocks/Cinder-NI/scons/SConscript', exports = 'env')
env = SConscript('../blocks/Cinder-BlobTracker/scons/SConscript', exports = 'env')
env = SConscript('../blocks/Cinder-OpenCV/scons/SConscript', exports = 'env')

SConscript(CINDER_PATH + '/scons/SConscript', exports = 'env')
